### ISSUE TITLE
Posters missing during first run

### ISSUE THREAD

**Issue by pierceizfierce** [JasonHHouse/gaps#170]
**Describe the bug**
Running GAPS for the first time. All movies are imported but all poster images are missing.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/69944364/93030667-61068580-f62d-11ea-9ee6-4d2fc0ecca73.JPG)

**Desktop (please complete the following information):**
 - OS: Docker Container
 - Browser: Chrome
 - Gaps Version: v0.7.5

**Comment by JasonHHouse** [comment]
I'll need the logs after Gaps has run a search.

**Comment by BEisem** [comment]
Seeing this here as well

**Comment by pierceizfierce** [comment]
> I'll need the logs after Gaps has run a search.

[GAPS log](https://github.com/JasonHHouse/gaps/files/5217744/GAPS.log)

**Comment by darkknight6722** [comment]
I too have the same problem

**Comment by JasonHHouse** [comment]
The mounted folder is unable to be written to. What OS is running docker and now did you configure the folder and mount point?

2020-09-14 04:24:03.552 ERROR 8 --- [taskScheduler-1] c.j.gaps.service.FileIoService           : Can't write to file /usr/data/movieIds.json

**Comment by wastingaeons** [comment]
Just chiming in here, I am seeing the same error in logs. Going back to the 'alpha' tag on Unraid, it works correctly (all same docker variables, paths, etc)

**Comment by JasonHHouse** [comment]
If you're seeing alpha work, you might want to try switching back to the mainline and going to configuration > Advanced > Delete All Stored Data > Delete. Then rescan plex and rerun gaps. This may be a storage configuration issue. 

Follow up question, the title of the issue is "first run", are the images loading after search is complete and refreshing the page?

**Comment by wastingaeons** [comment]
I've tried deleting stored data and starting completely fresh. The images don't show for me ever, and, the Recommended page becomes empty when refreshed after it finds missing movies (also without poster images)

Heres my log file. 
[gaps.log](https://github.com/JasonHHouse/gaps/files/5240724/gaps.log)

Only thing I see in browser console:
`
DevTools failed to load SourceMap: Could not load content for http://192.168.1.109:8484/js/libraries/sockjs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

`
DevTools failed to load SourceMap: Could not load content for http://192.168.1.109:8484/js/libraries/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

**Comment by JasonHHouse** [comment]
I saw this happening on my local machine. I'm not sure what happened but I rebuilt and pushed the container and it's fixed. I'm guessing the docker deploy was pushed and didn't build master on the commit I expected causing a bug. Try pulling the new docker and refreshing your libraries, that should fix the issue.

**Comment by wastingaeons** [comment]
Awesome, thank you! Can confirm it is working as intended.

**Comment by JasonHHouse** [comment]
Awesome!

**Comment by BayIsland757** [comment]
On Synology NAS with current image loaded, posters are still not working for me.

About screen reports v0.7.5

Interesting that the failed image has the following image address (doesnt seem complete to me to point to a specific image)

http://192.168.1.14:32400/?X-Plex-Token=XXXXXXXXXXXXXXXXXX

**Comment by JasonHHouse** [comment]
Try v0.8.0. The issue seemed to be a bad build of docker

**Comment by BEisem** [comment]
FWIW, for me on v0.8.0, the posters are missing on the Library page, but (ironically) they are not missing on the Missing page.

**Comment by BayIsland757** [comment]
Really Dumb question:  I normally pull from docker registry and select "Latest Version".... where else would be best place to get that from?  I thought that was the authoritative place to get most recent builds

Thanks in advance

**Comment by JasonHHouse** [comment]
I need full logs from Docker and JS to be able to fix this. 

DockerHub is the only spot to pull gaps from
